#!/bin/bash

clear
echo 
echo -e "\e[1m Love You All..!!!"
apt update
apt upgrade -y
apt install figlet -y
figlet Basic Installation
apt install toilet -y
apt install cowsay -y
apt install nano -y
apt install ruby -y
gem install lolcat
figlet -f big Good Job!!! | lolcat
echo
echo -e "\e[1m MarMu is the Best..!!!"
echo
echo -e "\e[1m\e[32m Creation by :\e[33m MarMu (Myanmar)"
